import { z } from "zod";

const side = z.enum(["BUY", "SELL"]);
const object = <T extends z.ZodRawShape>(shape: T) => z.object(shape).passthrough();

export const payloadByType = {
  signal: object({ symbol: z.string(), side, qty: z.number().optional(), intent: z.string().optional(), note: z.string().optional(), order: z.unknown().optional() }),
  "signal.cancel": object({ symbol: z.string(), intent: z.string().optional() }),
  "signal.latch_armed": object({ intent: z.string().optional(), reference: z.string(), offset: z.string(), streamAlias: z.string().optional(), name: z.string().optional(), armWindowMs: z.number().optional(), expiresAt: z.number().optional() }),
  "order.submit": object({
    orderId: z.string(),
    orderType: z.string(),
    symbol: z.string(),
    side,
    qty: z.number(),
    strategyId: z.string().optional(),
    timeInForce: z.string().optional(),
    createdTs: z.number().optional(),
    expiresAt: z.number().nullable().optional(),
    limitPrice: z.number().optional(),
    stopPrice: z.number().optional(),
    triggerPrice: z.number().optional(),
    onTrigger: z.string().optional(),
    trailAmount: z.number().optional(),
    trailMode: z.string().optional(),
    trailDistance: z.number().optional(),
    mfeThreshold: z.number().optional(),
    limitOffset: z.number().optional(),
    entryPrice: z.number().optional(),
    closesTicket: z.string().nullable().optional(),
    closesLegId: z.string().nullable().optional(),
    entry: z.unknown().optional(),
    parent: z.unknown().optional(),
    children: z.array(z.unknown()).optional(),
    leg1: z.unknown().optional(),
    leg2: z.unknown().optional(),
    takeProfit: z.number().optional(),
    stopLoss: z.unknown().optional(),
    takeProfitAst: z.unknown().nullable().optional(),
    stopLossAst: z.unknown().nullable().optional(),
    basis: z.unknown().optional(),
    legs: z.array(z.unknown()).optional(),
    target: z.unknown().optional(),
    deadline: z.number().optional(),
    onExpiry: z.string().optional(),
    layers: z.number().optional(),
    stackLayers: z.array(z.unknown()).optional(),
    withinMillis: z.number().nullable().optional(),
    hasOuterBracket: z.boolean().optional(),
    outerBracket: z.unknown().nullable().optional(),
  }),
  "order.accepted": object({ orderId: z.string(), brokerOrderId: z.string().optional() }),
  "order.filled": object({ orderId: z.string(), brokerOrderId: z.string().optional(), symbol: z.string(), price: z.number(), qty: z.number(), venueCosts: z.number().optional() }),
  "order.partially_filled": object({ orderId: z.string(), brokerOrderId: z.string().optional(), symbol: z.string(), side: side.optional(), price: z.number(), qty: z.number(), cumulativeQty: z.number(), venueCosts: z.number().optional(), typedVenueCosts: z.array(z.unknown()).optional() }),
  "order.cancelled": object({ orderId: z.string(), brokerOrderId: z.string().optional(), reason: z.string().optional() }),
  "order.rejected": object({ orderId: z.string(), brokerOrderId: z.string().optional(), reason: z.string() }),
  "order.modified": object({
    orderId: z.string(),
    brokerOrderId: z.string().optional(),
    changes: object({
      newQuantity: z.number().nullable().optional(),
      newLimitPrice: z.number().nullable().optional(),
      newStopPrice: z.number().nullable().optional(),
    }),
  }),
  trade: object({ orderId: z.string(), symbol: z.string(), side, price: z.number(), qty: z.number(), ts: z.number() }),
  "risk.rejected": object({ reason: z.string(), symbol: z.string().optional(), side: side.optional(), qty: z.number().optional() }),
  "risk.halted": object({ strategyId: z.string().nullable().optional(), reason: z.string() }),
  "risk.resumed": object({ strategyId: z.string().nullable().optional() }),
  "risk.snapshot": object({ strategyId: z.string().nullable().optional(), ts: z.number().optional() }),
  "strategy.started": object({
    strategyId: z.string(),
    ts: z.number().optional(),
    deployName: z.string().optional(),
    sourcePath: z.string().optional(),
    sourceSha256: z.string().optional(),
    dslVersion: z.number().optional(),
    runtimeMode: z.string().optional(),
    brokers: z.array(z.string()).optional(),
    symbols: z.array(z.string()).optional(),
    streams: z.array(z.unknown()).optional(),
    params: z.record(z.unknown()).optional(),
    defaults: z.record(z.unknown()).optional(),
    risk: z.record(z.unknown()).optional(),
  }),
  "strategy.stopped": object({ strategyId: z.string(), flatten: z.boolean().optional(), ts: z.number().optional() }),
  "insights.health": object({ sent: z.number(), failed: z.number(), dropped: z.number(), queued: z.number(), queueCapacity: z.number().optional(), batchSize: z.number().optional(), flushIntervalMs: z.number().optional(), maxPostAttempts: z.number().optional(), journalEnabled: z.boolean().optional(), journalPending: z.number().optional() }),
  "position.reconciled": object({ symbol: z.string(), before: z.number(), after: z.number() }),
  "position.opened": object({ symbol: z.string(), side, qty: z.number(), entryPrice: z.number().optional(), ticket: z.string().optional(), broker: z.string().optional(), strategyId: z.string().nullable().optional() }),
  "position.updated": object({ symbol: z.string(), side: side.optional(), qty: z.number(), entryPrice: z.number().optional(), currentPrice: z.number().optional(), ticket: z.string().optional(), broker: z.string().optional(), strategyId: z.string().nullable().optional() }),
  "position.closed": object({ symbol: z.string(), side: side.optional(), qty: z.number().optional(), exitPrice: z.number().optional(), ticket: z.string().optional(), broker: z.string().optional(), strategyId: z.string().nullable().optional() }),
  "position.valued": object({ symbol: z.string(), side: side.optional(), qty: z.number(), entryPrice: z.number().optional(), currentPrice: z.number().optional(), profit: z.number().optional(), ticket: z.string().optional(), broker: z.string().optional(), strategyId: z.string().nullable().optional() }),
  "balances.updated": object({ balances: z.record(z.number()) }),
  "gateway.unreachable": object({ detail: z.string() }),
  "broker.connected": object({ broker: z.string(), state: z.string().optional(), reason: z.string().optional(), ts: z.number().optional() }),
  "broker.disconnected": object({ broker: z.string(), state: z.string().optional(), reason: z.string().optional(), consecutiveFailures: z.number().optional(), ts: z.number().optional() }),
  "broker.reconnected": object({ broker: z.string(), state: z.string().optional(), reason: z.string().optional(), consecutiveFailures: z.number().optional(), ts: z.number().optional() }),
  "marketdata.connected": object({ source: z.string(), symbols: z.array(z.string()).optional(), state: z.string().optional(), reason: z.string().optional(), ts: z.number().optional() }),
  "marketdata.disconnected": object({ source: z.string(), symbols: z.array(z.string()).optional(), state: z.string().optional(), reason: z.string().optional(), ts: z.number().optional() }),
  "marketdata.reconnected": object({ source: z.string(), symbols: z.array(z.string()).optional(), state: z.string().optional(), reason: z.string().optional(), ts: z.number().optional() }),
  "snapshot.equity": object({ strategyId: z.string(), realized: z.number(), unrealized: z.number(), equity: z.number(), startingBalance: z.number() }),
  "snapshot.position": object({ strategyId: z.string(), symbol: z.string(),
    legs: z.array(object({ side, qty: z.number(), entryPrice: z.number(), entryTs: z.number() })) }),
  log: object({ level: z.enum(["DEBUG", "INFO", "WARN", "ERROR"]), logger: z.string(), message: z.string() }),
  "trade.closed": object({ orderId: z.string(), symbol: z.string(), side, qty: z.number(), price: z.number(),
    realized: z.number(), entryTs: z.number().optional(), ts: z.number() }),
  "state.account": object({
    broker: z.string(), currency: z.string(), balance: z.number(), equity: z.number(),
    margin: z.number().optional(), marginFree: z.number().optional(),
    openProfit: z.number().optional(), marginLevel: z.number().optional(),
    login: z.string().optional(), server: z.string().optional(), name: z.string().optional(),
  }),
  "state.positions": object({
    broker: z.string(),
    positions: z.array(object({
      ticket: z.string(), symbol: z.string(), side,
      qty: z.number(), entryPrice: z.number(), currentPrice: z.number().optional(),
      profit: z.number().optional(), swap: z.number().optional(),
      openedAt: z.number().optional(), strategyId: z.string().nullable().optional(),
    })),
  }),
  "broker.deal": object({
    broker: z.string(), dealTicket: z.string(), positionTicket: z.string().optional(),
    orderTicket: z.string().optional(), symbol: z.string().optional(), side: side.optional(),
    entry: z.string().optional(), qty: z.number(), price: z.number(),
    profit: z.number(), commission: z.number().optional(), swap: z.number().optional(),
    magic: z.number().optional(), comment: z.string().optional(), ts: z.number(),
    strategyId: z.string().nullable().optional(),
  }),
  "portfolio.configured": object({ portfolioId: z.string(), ts: z.number().optional() }),
  "portfolio.allocation.updated": object({ portfolioId: z.string(), ts: z.number().optional() }),
  "portfolio.exposure.updated": object({ portfolioId: z.string(), ts: z.number().optional() }),
  "portfolio.equity.updated": object({ portfolioId: z.string(), equity: z.number().optional(), realized: z.number().optional(), unrealized: z.number().optional(), ts: z.number().optional() }),
} as const;

export type EventType = keyof typeof payloadByType;
